# Here you can define the update schedule of Dependabot
# Dependabot is integrated on GitHub and can be deactivated in the GitHub settings

version: 2
updates:

- package-ecosystem: "docker"
  directory: "/docker"
  schedule:
    interval: daily
  open-pull-requests-limit: 99

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99

- package-ecosystem: "composer"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 99
