# ===== FOS User Bundle =====
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

login:
    path: login
    defaults:  { _controller: fos_user.security.controller:loginAction }
