name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      versionCode:
        description: 'Version Code - [Format: "Major.Minor.Patch", Example: "3.12.1]"'
        required: true

jobs:

  createRelease:
    name: New Release Pull Request
    runs-on: ubuntu-latest

    # Only create release branch in case the version number is valid
    if: '[[ ${{ github.event.inputs.versionCode }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5

      - name: Set Version Code
        run: |
          sed -i -E "s/APP_VERSION='[0-9]+\.[0-9]+\.[0-9]+'/APP_VERSION='${{ github.event.inputs.versionCode }}'/" .env

      - name: Create Pull Request to develop branch
        id: cpr-develop
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Prepare release v${{ github.event.inputs.versionCode }}
          committer: Catrobot <Catrobot@catroweb.github.com>
          title: 'Release v${{ github.event.inputs.versionCode }}'
          body: |
            ### Release v${{ github.event.inputs.versionCode }}

            Release ToDo List:
              - [X] Bump our version code
              - [ ] Update Changelog
              - [ ] Create new Release/Tag on GitHub

            This pull request is autogenerated using GitHub Actions.
            For more information checkout the action '.github/workflows/create_release_pull_request.yml'
          labels: automated, new-release
          branch: release/v${{ github.event.inputs.versionCode }}
          delete-branch: true
          reviewers: dmetzner
          base: develop

      - name: Create Pull Request to main branch
        id: cpr-main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Prepare release v${{ github.event.inputs.versionCode }}
          committer: Catrobot <Catrobot@catroweb.github.com>
          title: 'Release v${{ github.event.inputs.versionCode }}'
          body: |
            ### Release v${{ github.event.inputs.versionCode }}

            Release ToDo List:
              - [X] Bump our version code
              - [ ] Update Changelog
              - [ ] Create new Release/Tag on GitHub

            This pull request is autogenerated using GitHub Actions.
            For more information checkout the action '.github/workflows/create_release_pull_request.yml'
          labels: automated, new-release
          branch: release/v${{ github.event.inputs.versionCode }}
          delete-branch: true
          reviewers: dmetzner
          base: master

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
